configs:
  - classifier: sklearn.linear_model.LogisticRegression
    params:
      penalty: l2
      dual: false
      tol: 0.0001
      C: 1.0
      fit_intercept: true
      intercept_scaling: 1
  - classifier: sklearn.neighbors.KNeighborsClassifier
    params:
      n_neighbors: 5
      weights: uniform
      algorithm: auto
      leaf_size: 30
      p: 2
      metric: minkowski
  - classifier: sklearn.tree.DecisionTreeClassifier
    params:
      criterion: gini
      splitter: best
      min_samples_split: 2
      min_samples_leaf: 1
      min_weight_fraction_leaf: 0.0
      min_impurity_decrease: 0.0
      ccp_alpha: 0.0
  - classifier: sklearn.discriminant_analysis.LinearDiscriminantAnalysis
    params:
      solver: svd
      store_covariance: false
      tol: 0.0001
  - classifier: sklearn.ensemble.RandomForestClassifier
    params:
      n_estimators: 100
      criterion: gini
      min_samples_split: 2
      min_samples_leaf: 1
      min_weight_fraction_leaf: 0.0
      max_features: sqrt
